[[MiniZinc]]
arch = "aarch64"
git-tree-sha1 = "690c3bf035a2a7faba29f5bd93d7d084d8e36d2c"
os = "macos"

    [[MiniZinc.download]]
    sha256 = "f89cc077b63e13b1c98085835764008db4f599c11dda69f3d7d22594c28b9579"
    url = "https://github.com/JuliaBinaryWrappers/MiniZinc_jll.jl/releases/download/MiniZinc-v2.9.5+0/MiniZinc.v2.9.5.aarch64-apple-darwin.tar.gz"
[[MiniZinc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9fe8271efea8659749d65dd8e728f49e946243e7"
libc = "glibc"
os = "linux"

    [[MiniZinc.download]]
    sha256 = "06c71ec3e51be20b5869d149666dcd347576b26ae2863e4086910b32e696a938"
    url = "https://github.com/JuliaBinaryWrappers/MiniZinc_jll.jl/releases/download/MiniZinc-v2.9.5+0/MiniZinc.v2.9.5.aarch64-linux-gnu-cxx11.tar.gz"
[[MiniZinc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "972ab47cfc9d269c8020c4910bff767181efa02d"
libc = "musl"
os = "linux"

    [[MiniZinc.download]]
    sha256 = "7dae94afa43a0f6075206db3247046c08a7b2f34d1b340b3d736838a8a8141c2"
    url = "https://github.com/JuliaBinaryWrappers/MiniZinc_jll.jl/releases/download/MiniZinc-v2.9.5+0/MiniZinc.v2.9.5.aarch64-linux-musl-cxx11.tar.gz"
[[MiniZinc]]
arch = "aarch64"
git-tree-sha1 = "8b467bbca5a0b2d34952981fa29f1a9f9f95b0b3"
os = "freebsd"

    [[MiniZinc.download]]
    sha256 = "99fcb43322e97b5effc6c25430d828cb991f187c7adf36b053fd914e293603d3"
    url = "https://github.com/JuliaBinaryWrappers/MiniZinc_jll.jl/releases/download/MiniZinc-v2.9.5+0/MiniZinc.v2.9.5.aarch64-unknown-freebsd.tar.gz"
[[MiniZinc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "79c95e97ac01fbf924c8c72a9c73d97ab39d63db"
libc = "glibc"
os = "linux"

    [[MiniZinc.download]]
    sha256 = "541c742a3cb370d2f9f5723ddf183f1450407ab796f1b5a4359d524f8d33fc2a"
    url = "https://github.com/JuliaBinaryWrappers/MiniZinc_jll.jl/releases/download/MiniZinc-v2.9.5+0/MiniZinc.v2.9.5.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[MiniZinc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cd8ad75f2ce9fbd092b3ae73d00cd0ec390dfa5e"
libc = "musl"
os = "linux"

    [[MiniZinc.download]]
    sha256 = "3b6bc3f57359cff26b5dd4cac8879fd51d024dcbc266fabdfefe4c9dd8bcfd29"
    url = "https://github.com/JuliaBinaryWrappers/MiniZinc_jll.jl/releases/download/MiniZinc-v2.9.5+0/MiniZinc.v2.9.5.armv6l-linux-musleabihf-cxx11.tar.gz"
[[MiniZinc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4cf9d546c748ddf57344e8c238f40b3679edca8c"
libc = "glibc"
os = "linux"

    [[MiniZinc.download]]
    sha256 = "9c41bc792799e2e8d3bcef3c09596a1fb405f24ae5d4747563c05a786c732d97"
    url = "https://github.com/JuliaBinaryWrappers/MiniZinc_jll.jl/releases/download/MiniZinc-v2.9.5+0/MiniZinc.v2.9.5.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[MiniZinc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "63b4303a3306063642341882a8b86fa10520f55f"
libc = "musl"
os = "linux"

    [[MiniZinc.download]]
    sha256 = "02f727ddec99cc0de5ec67d2f308f5a89d38fea8daab8b209970674ed79ea67e"
    url = "https://github.com/JuliaBinaryWrappers/MiniZinc_jll.jl/releases/download/MiniZinc-v2.9.5+0/MiniZinc.v2.9.5.armv7l-linux-musleabihf-cxx11.tar.gz"
[[MiniZinc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fcc41bf41d9c389d7b15e71483d38358195e015e"
libc = "glibc"
os = "linux"

    [[MiniZinc.download]]
    sha256 = "320b9302324337a308babf2fafed406ce3d0120da7ea77b7a7dab091cad4d480"
    url = "https://github.com/JuliaBinaryWrappers/MiniZinc_jll.jl/releases/download/MiniZinc-v2.9.5+0/MiniZinc.v2.9.5.i686-linux-gnu-cxx11.tar.gz"
[[MiniZinc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5c98a1d412ffa46246ca50c2bfe18564cb4bc1ee"
libc = "musl"
os = "linux"

    [[MiniZinc.download]]
    sha256 = "09e922dea26da2a8919318392a457e6cc885d015b2a966af587735a78d4a71ac"
    url = "https://github.com/JuliaBinaryWrappers/MiniZinc_jll.jl/releases/download/MiniZinc-v2.9.5+0/MiniZinc.v2.9.5.i686-linux-musl-cxx11.tar.gz"
[[MiniZinc]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "709b417899725a1741951bc822ab29d8458842ac"
libc = "glibc"
os = "linux"

    [[MiniZinc.download]]
    sha256 = "c7f72e058314805ca6eebda7901a829eacbcedd77e6082e1ded4bf20c532d038"
    url = "https://github.com/JuliaBinaryWrappers/MiniZinc_jll.jl/releases/download/MiniZinc-v2.9.5+0/MiniZinc.v2.9.5.powerpc64le-linux-gnu-cxx11.tar.gz"
[[MiniZinc]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "47a238299d18db05492199cf20697dd2eb494b58"
libc = "glibc"
os = "linux"

    [[MiniZinc.download]]
    sha256 = "5a0aa29403b4ed3135c25148842f33b9b6cc8c76743d97d9ee8a69a498f6fb18"
    url = "https://github.com/JuliaBinaryWrappers/MiniZinc_jll.jl/releases/download/MiniZinc-v2.9.5+0/MiniZinc.v2.9.5.riscv64-linux-gnu-cxx11.tar.gz"
[[MiniZinc]]
arch = "x86_64"
git-tree-sha1 = "a0c8c3d1495b2646c0cfed844c7a5f4cea824449"
os = "macos"

    [[MiniZinc.download]]
    sha256 = "c9681b7c50d109212ef884455c019e10ea11599bd20c768362cd6c73343e893b"
    url = "https://github.com/JuliaBinaryWrappers/MiniZinc_jll.jl/releases/download/MiniZinc-v2.9.5+0/MiniZinc.v2.9.5.x86_64-apple-darwin.tar.gz"
[[MiniZinc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "37f6f9353210f653721808e6250825397840c23f"
libc = "glibc"
os = "linux"

    [[MiniZinc.download]]
    sha256 = "1ba047a357056330bbf87ea92c56eef600ca1e6041661d248a0002b33b8b4f50"
    url = "https://github.com/JuliaBinaryWrappers/MiniZinc_jll.jl/releases/download/MiniZinc-v2.9.5+0/MiniZinc.v2.9.5.x86_64-linux-gnu-cxx11.tar.gz"
[[MiniZinc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "67f6b4ce47ba7d40dab8929a2a478bcc9e86b92f"
libc = "musl"
os = "linux"

    [[MiniZinc.download]]
    sha256 = "4463385736e307e4e9a9e5d762c7c27f2d2bc45657f3d77a2ad951e671a0df3a"
    url = "https://github.com/JuliaBinaryWrappers/MiniZinc_jll.jl/releases/download/MiniZinc-v2.9.5+0/MiniZinc.v2.9.5.x86_64-linux-musl-cxx11.tar.gz"
[[MiniZinc]]
arch = "x86_64"
git-tree-sha1 = "44be8773007d74025bc01c4b890b181aa38a25b7"
os = "freebsd"

    [[MiniZinc.download]]
    sha256 = "1a995c9c2d566ac20ac12d58ce3665080f1058f14dbd89c6144775d15a40f74e"
    url = "https://github.com/JuliaBinaryWrappers/MiniZinc_jll.jl/releases/download/MiniZinc-v2.9.5+0/MiniZinc.v2.9.5.x86_64-unknown-freebsd.tar.gz"
[[MiniZinc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6521681f07ca802e8ac32e9f46db984095b41744"
os = "windows"

    [[MiniZinc.download]]
    sha256 = "d29eab04981cd14fd0d8aa8642c7c33f7f9ad23e48e172da8ec5946762cbca03"
    url = "https://github.com/JuliaBinaryWrappers/MiniZinc_jll.jl/releases/download/MiniZinc-v2.9.5+0/MiniZinc.v2.9.5.x86_64-w64-mingw32-cxx11.tar.gz"
